version: '3.9'

services:
  api:
    container_name: api
    image: api_express
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_USER=teste
      - DB_PASSWORD=123
      - DB_HOST=db
      - DB_PORT=5432
      - DB=db_users
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=db_users
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql